language: generic
dist: trusty
services:
    - docker

addons:
    apt:
        update: true

branches:
    only:
        - master
        - develop

before_install:
    - docker build -t vane98/personal-portfolio -f ./test.Dockerfile .

before_script:
    #PACKAGES NEEDED FOR SSH CONNECTION
    - sudo apt-get install sshpass
    # DISABLE HOST CHECKING IN SSH CONNECTION
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config

script:
    - docker run vane98/personal-portfolio npm test -- --watch=false

after_success:
    - docker build -t vane98/vnig-portfolio .
    - echo  "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push vane98/vnig-portfolio

deploy:
    skip_cleanup: true
    provider: script
    script: sshpass -p "$VPS_PASSWORD" ssh "$VPS_USER"@"$VPS_IP" "cd $VPS_DOCKER_PATH && sudo docker-compose down && "$VPS_PASSWORD"  && sudo docker image rm vane98/vnig-portfolio && "$VPS_PASSWORD"  && sudo docker-compose up --build -d && "$VPS_PASSWORD""
    on:
     branch: master


